export const CART_ADD_ITEM = "CART _ADD_ITEM"
export const CART_REMOVE_ITEM = "CART _REMOVE_ITEM"
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS"
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD"
